name: Build and Test

on:
  push:
    branches: [ $default-branch ]
  pull_request:
    branches: [ $default-branch ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: GitHub Action for Ember Testing
      uses: alexlafroscia/actions-ember-testing@v1.0.0
