name: CI/CD

on: [push]

jobs:
  test:
    name: 'Ember Test and Lint'
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: rwjblue/setup-volta@v1
    - uses: mydea/actions-ember-testing@v2
    - name: Install dependencies
      run: yarn install
    - name: Run tests
      run: yarn test
    - name: Lint JS
      run: yarn lint:js
    - name: Lint HBS
      run: yarn lint:hbs

  deploy:
    name: 'Deploy to Netlify'
    steps:
      - uses: jsmrcaga/action-netlify-deploy@v1.1.0
        with:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_DEPLOY_TO_PROD: true
          build_directory: 'dist/'
